name: Pull Request Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project files
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download and install FBXSDK files
        run: |
          # info
          id
          cat /etc/os-release
          uname -a

          # update
          sudo apt update ; sudo apt -y install gcc g++ make curl wget libxml2-dev zlib1g-dev

          # set up
          sudo mkdir -p /build
          sudo chown "$(whoami)" /build

          # download and build libiconv
          mkdir -p /build/libiconv
          cd /build/libiconv
          wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.11.tar.gz ; tar -xvf libiconv-1.11.tar.gz
          cd /build/libiconv/libiconv-1.11
          ./configure
          make
          make check
          sudo make install

          mkdir -p /build/fbxsdk
          wget https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_linux.tar.gz
          mkdir -p /usr/share/fbxsdk/2020.3.4 
          printf 'yes\nn\n' | /build/fbxsdk/fbx202034_fbxsdk_linux /usr/share/fbxsdk/2020.3.4

      - name: Build and run tests
        run: |
          ./all_build.sh
